### ISSUE TITLE
QEMU blocked by patching for over 1 minute

### ISSUE THREAD

**Issue by loyfan** [cloudlinux/libcare#47]
I am testing libcare with QEMU, and run into some problem.

The target is a QEMU VM with a 1TB rbd disk. The QEMU process contains 783 threads.
The patch file contains one modified function.
While patching, the QEMU process blocked  for over 1 minute.
From console output, I find it's because the patch_ensure_safety() function takes too much time.

Is ensure_safety necessary when we only modify the entry point of original function with just one jump call? I think the modification is too small to influence the safety.

Can you explain how the jump call influences the safety?
Thank you!

**Comment by paboldin** [comment]
Patching QEMU is a trick thing because it heavily uses coroutines. You will need to ensure that these are detected correctly.

You can override checking by patching the libcare code, but *always* do this on a test environment first.

First, the thing with jump call is that patches often change a few functions simultaneously and these functions rely on each other so that code manages data in a correct way. In order to ensure this and not break any internal structures we always check that all of the patched functions are not running during the patch.

Second, if your code patches some kind of `loop` function that is always running patching its first bytes wont have any effect because the function never returns to this place and never jump to the patched version.
